title: "Mahdi Salehzadeh"
theme: minima

author:
  email: "mahdi_salehzadeh[at]sfu[dot]ca"
    
minima:
  social_links:
    - platform: linkedin
      title: "LinkedIn"
      user_url: "https://www.linkedin.com/in/mahdi-salehzadeh-845478141/"
     
# Navigation Links
nav_links:
  - name: "Projects"
    url: "/Projects/"
  - name: "Short CV"
    url: "/ShortCV/"
  - name: "Publications"
    url: "/Publications/"
  - name: "Talks"
    url: "/Talks/"
