title: "Mahdi Salehzadeh"
theme: minima

baseurl: "/msalehzadeh" # Replace 'your-repo' with the repository name
url: "https://msalehzadeh.github.io" # Replace 'yourusername' with your GitHub username

email: "mahdi_salehzadeh@sfu.ca"
    
social_links:
  - platform: linkedin
    title: "LinkedIn"
    user_url: "https://www.linkedin.com/in/mahdi-salehzadeh-845478141/"
     
# Navigation Links
nav_links:
  - name: "About Me"
    url: "/README/"
  - name: "Projects"
    url: "/Projects/"
  - name: "Short CV"
    url: "/ShortCV/"
  - name: "Publications"
    url: "/Publications/"
  - name: "Talks"
    url: "/Talks/"
