title: "Mahdi Salehzadeh"
email: "mahdi_salehzadeh@sfu.ca"
  
theme: minima

header_pages:
  - Research.md
  - BriefCV.md
  - Publications.md 
  - Talks.md

 # Generate social links in footer.
social_links:
  - { platform: github,         user_url: "https://github.com/msalehzadeh" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=wQ4KU-YAAAAJ&hl=en" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/mahdi-salehzadeh-845478141/" }
 
  
