title: "Mahdi Salehzadeh"
email: "mahdi_salehzadeh@sfu.ca"

description: >
  M. Salehzadeh. All rights reserved.
  
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - Research.md
  - BriefCV.md
  - Publications.md 
  - Talks.md

social_links:
 - {platform: github,         user_url: "https://github.com/msalehzadeh" }
