title: "Mahdi Salehzadeh"
theme: minima

# Navigation Links
nav_links:
  - name: "About Me"
    url: "/AboutMe/"
  - name: "Projects"
    url: "/Projects/"
  - name: "Short CV"
    url: "/ShortCV/"
  - name: "Publications"
    url: "/Publications/"
  - name: "Talks"
    url: "/Talks/"
