title: "Mahdi Salehzadeh"
author:
  name: "Mahdi Salehzadeh"
  email: "mahdi_salehzadeh@sfu.ca"
  
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Navigation Links
nav_links:
  - name: "Projects"
    url: "/Projects/"
  - name: "Short CV"
    url: "/ShortCV/"
  - name: "Publications"
    url: "/Publications/"
  - name: "Talks"
    url: "/Talks/"

 # Generate social links in footer.
social_links:
  - { platform: github,         user_url: "https://github.com/msalehzadeh" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=wQ4KU-YAAAAJ&hl=en" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/mahdi-salehzadeh-845478141/" }
 
  
