title: "Mahdi Salehzadeh"
theme: minima
style: custom

sass:
  load_paths:
    - _sass

email: "mahdi_salehzadeh@sfu.ca"
    
social_links:
  - platform: linkedin
    title: "LinkedIn"
    user_url: "https://www.linkedin.com/in/mahdi-salehzadeh-845478141/"
     
# Navigation Links
nav_links:
  - name: "Projects"
    url: "/Projects/"
  - name: "Short CV"
    url: "/ShortCV/"
  - name: "Publications"
    url: "/Publications/"
  - name: "Talks"
    url: "/Talks/"
