title: "Mahdi Salehzadeh"
theme: minima
    
minima:
  social_links:
    - platform: google-scholar
      title: "Google Scholar"
      user_url: "https://scholar.google.com/citations?user=wQ4KU-YAAAAJ&hl=en"
    - platform: linkedin
      title: "LinkedIn"
      user_url: "https://www.linkedin.com/in/mahdi-salehzadeh-845478141/"
     
# Navigation Links
nav_links:
  - name: "Projects"
    url: "/Projects/"
  - name: "Short CV"
    url: "/ShortCV/"
  - name: "Publications"
    url: "/Publications/"
  - name: "Talks"
    url: "/Talks/"
